version: "3"

services:
  zookeeper:
    image: zookeeper:3.4
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: ches/kafka
    container_name: kafka
    ports:
      - "7203:7203"
      - "9092:9092"
    environment:
      - KAFKA_MESSAGE_MAX_BYTES=3000000
      - KAFKA_REPLICA_FETCH_MAX_BYTES=3100000
      - ZOOKEEPER_IP=zookeeper
    depends_on:
      - "zookeeper"

  topiccreation:
    image: ches/kafka
    depends_on:
      - "kafka"
    environment:
      - ZOOKEEPER_IP=zookeeper
    command: >
      sh -c "sleep 5 && kafka-topics.sh --create --topic commands --replication-factor 1 --partitions 3 --zookeeper $$ZOOKEEPER_IP:2181"
