apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kafkaproducer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafkaproducer
    spec:
      containers:
        - name: kafkaproducer
          image: kafkaproducer:latest
          imagePullPolicy: Never
          env:
          - name: TOPIC_NAME
            value: commands
          - name: KAFKA_URL 
            value: 10.97.138.50:9092
